language: go
sudo: required
go:
- 1.9.4

install:
- curl -Lo mmake https://github.com/codekoala/mmake/releases/download/v1.3.0/mmake_linux_amd64
- chmod 755 ./mmake

script:
- ./mmake update -I ./include
- dep ensure
- TAG=$TRAVIS_COMMIT ./mmake -I ./include all

deploy:
  provider: releases
  api_key:
    secure: KYIef/xMI1lkVAgkmrc6vj/xzhnjaQhYXh3oC+QOcZC7abYuCABfYAg08KU4FLjEsGCoHwWzIRRdIS3FrDQ0x1KS8oXaPAPhHdTISaviUdCofrL9L3gSJFQAw3ydCI3GT/GzASLTdD+SDcrt2TA8qApQUXrDsfvOx2b8MjZyzilTDwm27sFVrAOMObIAKXnWzmndVV0X9Z6xj0aKdeKdR11oq7LvvGrr9NpIoxSxrrBlTSUj3a1re7DM2cO1qUXbc7Y+tqKzNhT9TLqQQTlEXC1A39QRjNcJlVME3/HUkKJLB0dGAxKVvdFGdjN7n91flvPA9JiRapHIOhNFbyiJO/uaHLwV/MXCtdsvjAUVSDyCZxY8PXjqD27seTBj5cM1DyaHw+THViyToOrRxheUTy5yco5u4cGriq2LtU/JXUwoGYXzF+ExwnujWJu0gHMWw3tV7suLmoxykdXVHiB3NubYehsRFbwzLuNdoZOVB2xTh9gqKbvcBuXXJI5uBrSliRunRZVeZV5OaoRZ4yVaGth6Aw9bs025hiZ6hH/Qifm5O8WZfS0RTUQ38OhDwNR7/vM1gCXCkCalGZZ57fRRra07anpbSUhZcad0TbaF1Ma+Px1HrzeSg1WeJ4xMLkMj1KRwO50j/W4knbizw+hu1z83Nxz7mmXBTCbFfuRQ0T4=
  file_glob: true
  file: ./bin/*
  skip_cleanup: true
  overwrite: true
  on:
    repo: codekoala/aws-roll
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.9(\.[0-9]+)?$
